title: Your Practice Sherpa
email: holler(at)sherpas.io
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
seo_description: A navigational guide for innovative, clinical practice management
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://practicesherpa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: images/sherpas-dark-1650.svg
twitter_username: practiceSherpas
github_username:  practicesherpa
google_analytics:

# Build settings
markdown: kramdown
gems:
  - jekyll-compose
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-assets
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir:  _sass
  style:  compressed

excerpt_separator:  <!--excerpt-->
permalink: pretty
