title: Your Practice Sherpa
email: holler(at)sherpas.io
description: Your navigational aid to managing a 21st century clinical practice
baseurl: ""
url: "https://practicesherpa.github.io"
bg-logo: "/assets/images/sherpas-grey.svg"
logo: "/assets/images/sherpa-caps.svg"
twitter_username: Practice_Sherpa
github_username:  practicesherpa

# Build settings
markdown: kramdown
# theme: minima
host: localhost
port: 4000

gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
